B3:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-08-24_09-16-20','2021-08-25_10-35-00','2021-08-27_10-21-14'] 
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2']
  Stimulation: ['None','None','None']
  Sequences: [[2, 1, 3],[2, 1, 3],[2, 1, 3]]

B4:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-08-19_12-15-28','2021-08-20_12-24-04','2021-08-23_10-12-01','2021-08-24_14-25-45'] 
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Initial_Restday3']
  Stimulation: ['None','None','None','None']
  Sequences: [[3,2,1],[3,2,1],[3,2,1],[3,2,1]]

B5:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-09-10_10-30-11','2021-09-11_18-53-36','2021-09-13_17-37-37','2021-09-14_09-26-53','2021-09-15_09-26-06','2021-09-16_13-13-00','2021-09-17_14-24-22'] 
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal2']
  Stimulation: ['None','None','None','On-time','None','None','Delayed']
  channames_ripples: [[21],[6,14,22],[6,14,22],[14,22],[6,14,22],[6,14,22],[14,22]] #on-time & delayed: 14,22
  channames_cortex: [[29],[29],[29],[30],[29],[29],[30]] 
  Threshold: [7]
  Online_threshold: [11] #only no-stim for now
  Threshold_artefact: ['None','None','None',4,'None','None',5]
  Cortex_threshold: 5
  Sequences: [[2,1,3],[2,1,3],[2,1,3],[1,3,2],[1,3,2],[1,3,2],[3,2,1]]  
  fs: 4000
  
B6:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-09-17_09-48-11','2021-09-18_12-27-36','2021-09-20_11-30-35']
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2']
  Stimulation: ['None','None','None']
  Sequences: [[3,2,1],[3,2,1],[3,2,1]]
  
B7:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-10-18_10-17-12','2021-10-20_09-47-08']
  Allsessiontypes: ['Initial','Initial_Restday1']
  Stimulation: ['None','None']
  Sequences: [[3,2,1],[3,2,1]]
  
B9:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-11-12_10-45-14','2021-11-13_11-39-08','2021-11-14_16-31-43','2021-11-15_13-10-13','2021-11-16_11-20-50','2021-11-17_10-56-11','2021-11-18_09-10-13']
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal2']
  Stimulation: ['None','None','None','Delayed','None','None','On-time']
  channames_ripples: [[22,23],[1,22],[1,22],[2,23],[1,22],[1,22],[2,23]] #on-time and delayed: [2,23]
  channames_cortex: [[31],[31],[31],[31],[31],[31],[31]] 
  Threshold: [7]
  Online_threshold: [14] #only no-stim for now
  Threshold_artefact: ['None','None','None',6,'None','None',6]
  Cortex_threshold: 5
  Sequences: [[3,2,1],[3,2,1],[3,2,1],[2,1,3],[2,1,3],[2,1,3],[1,3,2]]
  fs: 4000
    
B10:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-11-19_08-45-23','2021-11-20_14-51-53','2021-11-21_16-02-52','2021-11-22_14-26-26','2021-11-23_12-29-52','2021-11-24_16-05-02','2021-11-25_16-42-41','2021-11-26_12-12-00']
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Initial_Restday3','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal2']
  Stimulation: ['None','None','None','None','On-time','None','None','Delayed']
  channames_ripples: [[1],[3,10],[3,10],[3,10],[15],[15],[15],[15]]
  channames_cortex: [[18],[18],[18],[18],[18],[18],[18],[18]]
  Threshold: [8]
  Online_threshold: [14] #only no-stim for now
  Threshold_artefact:  ['None','None','None','None',6,'None','None',7]
  Cortex_threshold: 5
  Sequences: [[1,3,2],[1,3,2],[1,3,2],[1,3,2],[3,2,1],[3,2,1],[3,2,1],[2,1,3]]
  fs: 4000
  
B11:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-12-10_10-47-48','2021-12-11_17-49-57','2021-12-12_12-24-37','2021-12-13_10-58-52','2021-12-14_11-06-04'] #,'2021-12-15_17-09-21']
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1'] #,'Reversal1_Restday2']
  Stimulation: ['None','None','None','Delayed','None'] #,'None']
  channames_ripples: [[9,10],[3,10,26],[3,10],[5,10],[26]]  #delayed session should actually be [5,10] but the array sized of 5 and 10 don't match
  channames_cortex: [[29],[29],[29],[29],[29]] 
  Threshold: [7]
  Online_threshold: [14] #only no-stim for now
  Threshold_artefact: ['None','None','None',6,'None']
  Cortex_threshold: 5
  Sequences: [[2,1,3],[2,1,3],[2,1,3],[3,2,1],[3,2,1],[3,2,1]]
  fs: 4000
    
B12:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-12-14_15-14-44','2021-12-15_11-14-02','2021-12-16_09-48-10','2021-12-17_10-27-44']
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1']
  Stimulation: ['None','None','None','On-time']
  channames_ripples: [[11],[4,8,11],[4,8,11],[4,8]] #['8','8','8','8'] #['4','8'] 
  channames_cortex: [[29],[29],[29],[30]]
  Threshold: [7]
  Online_threshold: [14] #only no-stim for now
  Threshold_artefact: ['None','None','None',4]
  Cortex_threshold: 5
  Sequences: [[3,2,1],[3,2,1],[3,2,1],[1,3,2]]  
  fs: 4000
    
B13:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2021-12-19_14-37-12','2021-12-20_15-36-03','2021-12-21_14-10-20','2021-12-22_13-56-38','2021-12-23_14-39-00','2021-12-24_13-01-01'] 
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal2']
  Stimulation: ['None','None','None','On-time','None','Delayed']
  Sequences: [[2, 1, 3],[2, 1, 3],[2, 1, 3],[3,2,1],[3,2,1],[1,3,2]]
  
B14:
  topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
  Alldates: ['2022-02-16_14-14-12','2022-02-17_15-06-28','2022-02-18_16-42-32','2022-02-19_14-39-52','2022-02-20_14-35-41','2022-02-21_13-37-05','2022-02-22_14-00-16']
  Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal2']
  Stimulation: ['None','None','None','Delayed','None','None','On-time']
  channames_ripples: [[9,11],[2,9],[2,9],[2],[2,9],[2,9],[9]] #ontime & delayed: [2,9]
  channames_cortex: [[18],[18],[18],[18],[18],[18],[18]]
  Threshold: [7]
  Online_threshold: [14] #only no-stim for now
  Threshold_artefact: ['None','None','None',7,'None','None',6]
  Cortex_threshold: 5
  Sequences: [[3,2,1],[3,2,1],[3,2,1],[2,1,3],[2,1,3],[2,1,3],[1,3,2]]
  fs: 32000  
  
B17:
    topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
    Alldates: ['2022-04-05_11-09-44','2022-04-06_15-06-29','2022-04-07_17-06-16','2022-04-08_15-25-46','2022-04-09_18-53-24','2022-04-10_18-31-30','2022-04-11_15-03-41']
    Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal2']
    Stimulation: ['None','None','None','Delayed','None','None','On-time']
    channames_ripples: [[11],[11],[11],[11],[11],[11],[11]]
    channames_cortex: [[2],[2],[2],[2],[2],[2],[2]]
    Threshold: [8]
    Online_threshold: [14] #only no-stim for now
    Threshold_artefact: ['None','None','None',4,'None','None',4]
    Cortex_threshold: 5
    Sequences: [[1,3,2],[1,3,2],[1,3,2],[2,1,3],[2,1,3],[2,1,3],[3,2,1]]
    fs: 4000
    
B18:
    topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
    Alldates: ['2022-04-08_11-06-36','2022-04-09_15-34-15','2022-04-10_19-34-21' ,'2022-04-11_10-50-32','2022-04-12_11-33-39', '2022-04-13_10-56-06']
    Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal1_Restday2']
    Stimulation: ['None','None','None','On-time','None','None']
    channames_ripples: [[1,3],[1,5,9],[23],[1,21],[23],[23]] #on-time:[1,21] 1,5,9, 21 & 23 should have ripples
    channames_cortex: [[31],[25],[25],[31],[25],[25]] 
    Threshold: [7]
    Online_threshold: [14] #only no-stim for now
    Threshold_artefact: ['None','None','None',6,'None','None']
    Cortex_threshold: 5
    Sequences: [[2,1,3],[2,1,3],[2,1,3],[3,2,1],[3,2,1],[3,2,1],[1,3,2]]
    fs: 32000
    
B20:
    topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
    Alldates: ['2022-05-13_08-08-20','2022-05-14_12-19-13','2022-05-15_13-58-59','2022-05-16_12-10-03','2022-05-18_13-54-32','2022-05-19_09-12-59','2022-05-20_09-34-54','2022-05-21_16-24-23','2022-05-22_16-14-34','2022-05-23_09-59-24']
    Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Initial_Restday3','Initial_Restday4','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal1_Restday3','Reversal2']
    Stimulation: ['None','None','None','None','None','On-time','None','None','None','Delayed']
    channames_ripples: [[17],[17],[17],[17],[5],[5],[5],[5],[5],[5]]
    channames_cortex: [[22],[22],[22],[22],[9],[9],[9],[9],[9],[9]]
    Threshold: [9]
    Online_threshold: [16] #only no-stim for now
    Threshold_artefact: ['None','None','None','None','None',5,'None','None','None',5]
    Cortex_threshold: 10
    Sequences: [[1,3,2],[1,3,2],[1,3,2],[1,3,2],[1,3,2],[3,2,1],[3,2,1],[3,2,1],[3,2,1],[2,1,3]]
    fs: 4000
  
B21:
    topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
    Alldates: ['2022-07-05_13-43-55','2022-07-10_15-06-43','2022-07-11_14-04-17','2022-07-12_13-50-45','2022-07-13_15-27-57','2022-07-14_09-47-09','2022-07-15_09-22-40'] #,'2022-07-18_09-29-30']
    Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal2','Reversal2_Restday1']
    Stimulation: ['None','None','None','Delayed','None','None','On-time','None']
    channames_ripples: [[5,7,17,19],[5,9,17],[5,9,17],[5,9,17],[5,9,17],[5,9,17],[5,9,17],[5]]
    channames_cortex: [[1],[1],[1],[1],[25],[25],[1],[25]]
    Threshold: [9]
    Online_threshold: [16] #only no-stim for now
    Threshold_artefact: ['None','None','None',6,'None','None',6,'None']
    Cortex_threshold: 20
    Sequences: [[3,2,1],[3,2,1],[3,2,1],[2,1,3],[2,1,3],[2,1,3],[1,3,2],[1,3,2],[1,3,2]]
    fs: 4000
    
B23:
   topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
   Alldates: ['2022-08-17_12-22-01','2022-08-18_09-41-04','2022-08-19_10-01-53','2022-08-20_10-52-03','2022-08-21_09-46-29','2022-08-22_10-40-54','2022-08-23_10-33-59','2022-08-24_10-26-58']
   Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Reversal1','Reversal1_Restday1','Reversal1_Restday2','Reversal1_Restday3','Reversal2']
   Stimulation: ['None','None','None','On-time','None','None','None','Delayed']
   channames_ripples: [[17,21,25],[17,21,25],[17,21,25],[17],[17,21,25],[17,21,25],[17,21,25],[17,21,25]]
   channames_cortex: [[11],[15],[14],[14],[14],[14],[14],[14]]
   Threshold: [9]
   Online_threshold: [16] #only no-stim for now
   Threshold_artefact: ['None','None','None',5,'None','None','None',5]
   Cortex_threshold: 12
   Sequences: [[2,1,3],[2,1,3],[2,1,3],[1,3,2],[1,3,2],[1,3,2],[1,3,2],[3,2,1]]
   fs: 4000

B24:
   topfolder: '/mnt/fk-fileserver/Project_PFC_optogenetics/'
   Alldates: ['2022-08-09_12-05-15','2022-08-10_12-56-52','2022-08-11_13-20-46','2022-08-12_12-31-44','2022-08-13_12-05-56','2022-08-14_15-07-02','2022-08-15_11-56-09','2022-08-15_15-46-16','2022-08-19_11-58-16','2022-08-20_15-16-17','2022-08-21_14-03-17']
   Allsessiontypes: ['Initial','Initial_Restday1','Initial_Restday2','Initial_Restday3','Initial_Restday4','Reversal1','Reversal1_Restday1a','Reversal1_Restday1b','Reversal1_Restday2','Reversal1_Restday3','Reversal2']
   Stimulation: ['None','None','None','None','None','Delayed','None','None','None','None','On-time']
   channames_ripples: [[4,28],[4],[4],[4],[4],[4],[4],[4],[4],[4],[4]]
   channames_cortex: [[16],[16],[16],[16],[16],[16],[16],[16],[16],[16],[16]]
   Threshold: 16
   Cortex_threshold: 12
   Sequences: [[3,2,1],[3,2,1],[3,2,1],[3,2,1],[3,2,1],[1,3,2],[1,3,2],[1,3,2],[1,3,2],[1,3,2],[2,1,3]]
   fs: 4000